DROP DATABASE IF EXISTS  VENTALIBROS;

CREATE DATABASE VENTALIBROS;

USE VENTALIBROS;

CREATE TABLE CATEGORIAS(
	ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DE LA CATEGORIA'
	, NOMBRE VARCHAR(45) NOT NULL COMMENT 'NOMBRE DE LA CATEGORIA'
	, PRIMARY KEY PK_CATEGORIAS_ID (ID)
);

CREATE TABLE LIBROS (
  ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DEL LIBRO'
  , NOMBRE VARCHAR(45) NOT NULL COMMENT 'NOMBRE DEL LIBRO'
  , AUTOR VARCHAR(100) NOT NULL COMMENT 'AUTOR DEL LIBRO'
  , PRECIO FLOAT NOT NULL COMMENT 'PRECIO DEL LIBRO'
  , EXISTENCIA INT NOT NULL COMMENT 'EXISTENCIA DE LIBROS'
  , IDCATEGORIA INT NOT NULL COMMENT 'ID DE LA CATEGORIA DEL LIBRO'
  , PRIMARY KEY PK_LIBROS_ID (ID)
  , CONSTRAINT FK_LIBROS_IDCATEGORIA 
  		FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS (ID)
);

CREATE TABLE ROLES (
	ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DEL ROL'
	, NOMBRE VARCHAR(45) NOT NULL COMMENT 'NOMBRE DEL ROL'
	, PRIMARY KEY PK_ROLES_ID (ID)
);

CREATE TABLE USUARIOS (
  ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DEL USUARIO'
  , USUARIO VARCHAR(20) NOT NULL COMMENT 'USUARIO'
  , CONTRASENIA VARCHAR(128) NOT NULL COMMENT 'CONTRASEÑA DEL USUARIO ALMACENADA EN UN HASH'
  , ESTADO ENUM('1', '0') NOT NULL COMMENT '0 - DESACTIVADO, 1 - ACTIVADO'
  , IDROL INT NOT NULL COMMENT 'IDENTIFICADOR DEL ROL'
  , PRIMARY KEY PK_USUARIOS_ID (ID)
  , CONSTRAINT FK_USUARIOS_IDROL
    	FOREIGN KEY (IDROL) REFERENCES ROLES (ID)
   , UNIQUE KEY UN_USUARIOS_USUARIO(USUARIO)
);

CREATE TABLE CLIENTES (
  ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DEL CLIENTE'
  , NOMBRE VARCHAR(45) NOT NULL COMMENT 'NOMBRE DEL CLIENTE'
  , APELLIDO VARCHAR(45) NOT NULL COMMENT 'APELLIDO DEL CLIENTE'
  , CORREOELECTRONICO VARCHAR(50) NOT NULL COMMENT 'CORREO ELECTRONICO DEL CLIENTE'
  , IDUSUARIO INT NOT NULL COMMENT 'IDENTIFICADOR DEL USUARIO'
  , PRIMARY KEY PK_CLIENTES_ID (ID)
  , CONSTRAINT FK_CLIENTES_IDUSUARIO
		FOREIGN KEY (IDUSUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE ORDENESCABECERA (
  ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DE LA CABECERA DE ORDEN'
  , FECHA DATETIME NOT NULL COMMENT 'FECHA DE LA ORDEN'
  , IVA FLOAT NOT NULL COMMENT 'IVA DE LA ORDEN'
  , TOTAL FLOAT NOT NULL COMMENT 'TOTAL DE LA ORDEN'
  , IDCLIENTE INT NOT NULL COMMENT 'IDENTIFICADOR DEL CLIENTE'
  , PRIMARY KEY PK_ORDENESCABECERA_ID (ID)
  , CONSTRAINT FK_ORDENESCABECERA_IDCLIENTE
    	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (ID)
);

CREATE TABLE ORDENESDETALLE (
  ID INT NOT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DEL DETALLE DE ORDEN'
  , CANTIDAD INT NOT NULL COMMENT 'CANTIDAD DE LA ORDEN DE DETALLE'
  , PRECIO FLOAT NOT NULL COMMENT 'PRECIO DEL DETALLE'
  , IMPORTE FLOAT NOT NULL COMMENT 'IMPORTE DEL DETALLE'
  , IDORDENCABECERA INT NOT NULL COMMENT 'ID DE LA CABECERA AL QUE PERTENCE EL DETALLE'
  , IDLIBRO INT NOT NULL COMMENT 'IDENTIFICADOR DEL LIBRO'
  , PRIMARY KEY PK_ORDENESDETALLE_ID (ID)
  , CONSTRAINT FK_ORDENESDETALLE_IDORDENCABECERA
 	   FOREIGN KEY (IDORDENCABECERA) REFERENCES ORDENESCABECERA (ID)
  , CONSTRAINT FK_ORDENDENESTALLE_IDLIBRO
    	FOREIGN KEY (IDLIBRO) REFERENCES LIBROS (ID)
);